### ISSUE TITLE
Support 2.13

### ISSUE THREAD

**Issue by Fristi** [vovapolu/scaluzzi#11]
Thanks for this great linting lib, would it be hard to upgrade to 2.13?

**Comment by enzief** [comment]
I'm finding time to look into that (I am not a maintainer).

**Comment by vovapolu** [comment]
Is scalafix published for 2.13? It shouldn't be hard to release scaluzzi for 2.13 if scalafix is available.

**Comment by enzief** [comment]
I think yes
https://github.com/scalacenter/scalafix/commit/d5d23dbf37208533254067ddf1cea3dca6904b2b

**Comment by vovapolu** [comment]
Hmm, `scalafix-core` wasn't released for 2.13 https://mvnrepository.com/artifact/ch.epfl.scala/scalafix-core. There's also the similar issue in scalafix repo https://github.com/scalacenter/scalafix/issues/982. Personally I don't understand why there's no support for 2.13 and why do you need 2.13 support, because sbt, as I understand, runs quite fine with 2.12 for now.

**Comment by Fristi** [comment]
I see, also works for me with 2.13 closing
